vich_uploader:
    db_driver: orm
    mappings:
        organization_image:
            uri_prefix: /images/organization
            upload_destination: "%env(UPLOAD_IMAGE_PATH)%"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
