vich_uploader :
    pilote_db : orm
    mappings :
        organization:
        uri_prefix: /images/organization
        upload_destination: "%kernel.project_dir%/public/storage/images/organizations"
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer  
        
