vich_uploader:
    db_driver: orm
    mappings:
        organizationImage:
            uri_prefix: /storage/images/organizations
            upload_destination: "%kernel.project_dir%/public/storage/images/organizations/"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
  