version: "3.7"
services:
  composer:
    image: composer
    volumes:
      - ./app:/app
    user: 1000:1000
    # command: composer install --ignore-platform-reqs --no-scripts
    # command: composer require symfony/ux-twig-component
    # command: composer require dompdf/dompdf
    command: composer update --ignore-platform-reqs --no-scripts

  php:
    build: ./.docker/php
    working_dir: /var/www/
    env_file: ./app/.env
    volumes:
      - ./app:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: php-fpm
    user: 1000:1000
    depends_on:
      composer:
        condition: service_completed_successfully
      postgres:
        condition: service_started

  postgres:
    image: postgres:15.2
    env_file: ./app/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./app/:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  webpack_installer:
    image: node:20.8.1-alpine3.18
    volumes:
      - ./app:/home/node/app
    user: 1000:1000
    working_dir: /home/node/app
    command: npm i

  webpack:
    image: node:20.8.1-alpine3.18
    volumes:
      - ./app:/home/node/app
    tty: true
    working_dir: /home/node/app
    command: npm run watch
    user: 1000:1000
    depends_on:
      webpack_installer:
        condition: service_completed_successfully
      composer:
        condition: service_completed_successfully

  adminer:
    image: adminer:latest
    ports:
      - 8888:8080

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080

volumes:
  postgres-data:
